### ISSUE TITLE
Make this module up-to-date and to the Fastify standard

### ISSUE THREAD

**Issue by mcollina** [fastify/send#2]
This module was forked due to https://github.com/fastify/fastify-static/issues/352.

Given the status of maintenance of `send()` and how badly out of date it was in its deps, I think we could do some good work here to bring this module up to our standards.

**Comment by Uzlopak** [comment]
Can somebody please add this repo to @fastify/libraries  please?

**Comment by mcollina** [comment]
Yes

**Comment by jsumners** [comment]
> Can somebody please add this repo to @fastify/libraries please?

Done.

**Comment by Uzlopak** [comment]
Is refactoring part of this issue?

We got already
- use of our workflows
- use standardjs
- use tap as test runner
- 100% code coverage
- support of lts versions of node

What left is
- #15 
- maybe remove all those packages which are made for streams issue of node 0.8.0 like on-finished, destroy
- maybe remove http-errors package as it is in my benchmarks a performance bottleneck
- integrate some of the dependencies like fresh and range
- general perf optimizations
- check if we can take open PRs of the original send repo

**Comment by mcollina** [comment]
I'd be ok to cut a v2 without #15, and then work on a v3 for it.

**Comment by Uzlopak** [comment]
After #27 we could integrate parseRange and fresh package.

**Comment by Uzlopak** [comment]
Imho all relevant pieces are now in the repo. We could start transplanting open PRs from the original repo to our fork. But maybe @climba03003 wants to implement #15 ?

**Comment by mcollina** [comment]
https://github.com/fastify/send/issues/15 is super important.

**Comment by mcollina** [comment]
I think we can close this.

**Comment by mcollina** [comment]
Should we release v2?

**Comment by climba03003** [comment]
> Should we release v2?

Yes, #15 would completely change the API. And `v2` should be compatible to the original one.
