### ISSUE TITLE
"files" field removed from package.json. Test files etc. included in published package

### ISSUE THREAD

**Issue by RubenStoesser** [fastify/send#42]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

1.0.0

### Stopped working in version

2.0.0

### Node.js version

all

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.2.1

### 💥 Regression Report

In a PR released with `2.0.0` (https://github.com/fastify/send/pull/6) the `files` field in package.json was removed. 

Due to this all files of the repo are now included in the published npm package (tests, benchmarks, examples etc.).

### Steps to Reproduce

I only noticed this because in our CI environment Mend security scans started failing with this error message while resolving the dependency tree:

```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: node_modules/@fastify/send/test/fixtures/snow ???
```

This seems to be caused by the snowman emoji in this folder name:
https://github.com/fastify/send/tree/master/test/fixtures/snow%20%E2%98%83

The issue wasn't present before because the entire tests folder was excluded from the published npm package.

### Expected Behavior

Usually only relevant production files need to be included in the published package. If the change was on purpose another quick-fix for this specific issue would be to remove the non-standard character from the "snow" folder name

**Comment by climba03003** [comment]
> If the change was on purpose another quick-fix for this specific issue would be to remove the non-standard character from the "snow" folder name

The changes is on purpose and those characters exists also on purpose for testing the characters handling.

**Comment by marccremer** [comment]
The issue https://github.com/fastify/skeleton/issues/42 points out that we should **NOT** include test folders, or have I misunderstood something?

![image](https://github.com/fastify/send/assets/56308724/4d340581-ce09-405e-8f5b-91425126e01f)

**Comment by Eomm** [comment]
> we should NOT include test folders, or have I misunderstood something?

You have misunderstood:

<img width="442" alt="image" src="https://github.com/fastify/send/assets/11404065/6fb1c868-b7a3-4197-b168-a96d6f90c6be">

Anyway, that image shows this pinojs issue: https://github.com/pinojs/pino/pull/1588
That org is not the fastify one, so org has its rules.
