### ISSUE TITLE
Please remove emoji from dir path

### ISSUE THREAD

**Issue by Stormpass** [fastify/send#51]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

here is the location:
[snow ☃] https://github.com/fastify/send/tree/master/test/fixtures/snow ☃

this will cause build error:  electron wix build error

wix file does not support unicode, it will throw an error like

if keep this emoji, fasify will not support in electron(wix scene)

> A string was provided with characters that are not available in the specified
database code page '1252'. Either change these characters to ones that exist in
the database's code page, or update the database's code page by modifying one of
the following attributes: Product/@codepage, Module/@codepage, Patch/@codepage,
PatchCreation/@codepage, or WixLocalization/@codepage.

**Comment by mcollina** [comment]
I don't understand this issue. Can you provide a little bit more context?

How is a test file impacting your application?

**Comment by Stormpass** [comment]
I have fasitify running in the electron environment.
and packaged it with maker-wix.
While the packaging is going on, electron will copy all the dependencies of the node_module into the resource package
maker-wix generates xml paths for each resource and stores them in a wix file.
The @fastify/send package is in my dependencies, so it gets copied into the electron package in its entirety (including the test folder).
I ended up generating a wix file with this path "snow ☃" but my wxs file doesn't support unicode.
See my screenshot
![image](https://github.com/fastify/send/assets/31079748/ca592085-8248-4af2-a2ae-c9a4a0e6b490)

For normal node apps, this doesn't cause problems, but for electron, it can cause problems。
So I suggest
Remove the test folder from the npm distribution or change the folder name

**Comment by Uzlopak** [comment]
Hmm. Well, i kind of dislike the idea of removing this file as it is part of our tests. 
Did you report this issue in the maker-wix repo?
Is it a potential solution to install rimraf as dev dependency and add a npm script calling "rimraf ./node_modules/send/test"?

**Comment by Eomm** [comment]
Could you remove the `**/test/*` folder from your build step?

**Comment by Stormpass** [comment]
Thanks, I had removed this folder in the build step before I raised this issue.
Suggestion: Anyone who has encountered this problem using fastify in electron, if unicode is blocking the build step, please add a regular expression to the array
forge.config.js -> packagerConfig -> ignore

/^\/node_modules\/@fastify\/send\/test/

electron will no longer copy the folder containing the emoji names.

I'm going to close this issue.

**Comment by DannyvanHolten** [comment]
Not sure why test files are bundled inside the package.
