### ISSUE TITLE
Folder name with emoji causes compression errors.

### ISSUE THREAD

**Issue by Niranjan-A-S** [fastify/send#78]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.0

### Node.js version

20.14

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

The emoji "☃" in the "test/fixtures/snow ☃" is causing issues while trying to compress the node_modules of the application using the window's native compress tool.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Niranjan-A-S** [comment]
Please follow the steps to reproduce.

- Make sure you have @fastify/send in your node_modules.
- Try to compress node_modules folder directly or the parent folder with the windows native compress tool. (Don't use 7-Zip or any other tools.)
- You will be prevented from completing the action with a prompt. Please find the snapshot attached.

![Screenshot 2024-07-09 153619](https://github.com/fastify/send/assets/82747734/01a33cee-f781-428e-8e6b-0242b089d4f6)

**Comment by Eomm** [comment]
Duplicate https://github.com/fastify/send/issues/51 ?

I mean, save time by ignoring `test/` folders

**Comment by Niranjan-A-S** [comment]
Requires an extra layer of step to remove the test folder during the build process. The "snow ☃" can be renamed right?

**Comment by jsumners** [comment]
> Requires an extra layer of step to remove the test folder during the build process. The "snow ☃" can be renamed right?

No. https://github.com/fastify/send/commit/8a44fe6f117ba947647ed16d8a6696cef9fdafb8

**Comment by Niranjan-A-S** [comment]
Great!

**Comment by Fdawgs** [comment]
Closing as this is not an issue with the package itself but external tooling.
